CREATE DATABASE PROJECTETEC;

USE PROJECTETEC;

CREATE TABLE TBL_CADASTRO(
ID_ETEC	  BIGINT       PRIMARY KEY auto_increment NOT NULL,
COD_ETEC  INT 	   	               NOT NULL,
NOME_ETEC VARCHAR(100)  		   NOT NULL,
CEP_ETEC  VARCHAR(8)			   NOT NULL,
END_ETEC  VARCHAR(100)             NOT NULL,
LAT_ETEC  DOUBLE				   NOT NULL,
LON_ETEC  DOUBLE                   NOT NULL,
BAI_ETEC  VARCHAR(50)              NOT NULL,
CID_ETEC  VARCHAR(30)              NOT NULL,
DT_CRIA   DATETIME                 
);

DROP TABLE TBL_CADASTRO

select * from TBL_CADASTRO